version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: qr_code_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: qr_code_generator
      MYSQL_USER: qruser
      MYSQL_PASSWORD: qrpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
volumes:
  mysql_data:
