version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: qr_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: qr_generator
      MYSQL_USER: qr_user
      MYSQL_PASSWORD: qr_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data: